# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

workflows:
  main:
    jobs:
      - test:
          version: '16.20'
          filters:
            branches:
              only:
                - master
                - dev
      - test:
          version: '18.17'
          filters:
            branches:
              only:
                - master
                - dev
      - test:
          version: '20.5'
          filters:
            branches:
              only:
                - master
                - dev

jobs:
  test:
    executor: node/default
    parameters:
      version:
        type: string
    docker:
      - image: cimg/node:<< parameters.version >>
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: sudo npm install -g npm@^9
      - run: npm install
      - run: npm run lint
      - run: npm run citest
      - run: npm install coveralls --no-save
      - coveralls/upload:
          coverage_file: ./coverage/lcov.info
